WebApplication1/Controllers/CartController.cs
using DAL.Models;
using BLL.Services;
using Microsoft.AspNetCore.Mvc;
using BLL.Interfaces;
using BLL.DTO;
using DAL.Interface;
using AutoMapper;
using Microsoft.VisualBasic;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private IGamesService gamesService;
        private ICartService cartService;
        private IClientService clientService;
        private IStoreService storeService;
        public CartController(IGamesService gamesService, ICartService cartService, IClientService clientService, 
            IStoreService storeService)
        {
            this.gamesService = gamesService;
            this.cartService = cartService;
            this.clientService = clientService;
            this.storeService = storeService;
        }

        public IActionResult RemoveFromCart(int gameId)
        {
            List<CartDTO> listcart = cartService.GetAll();
            List<ClientDTO> clientDTOs = clientService.GetAll();

            string userId = HttpContext.Session.GetString("userId");
            ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

            var findCart = listcart
                            .Where(x => x.GameId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            if (findCart != null)
            {
                cartService.DeleteById(findCart);
            }

            return RedirectToAction("CheckCart");
        }
        public IActionResult AddToCart(int gameId)
        {
            List<CartDTO> listcart = cartService.GetAll();
            List<StoreDTO> stores = storeService.GetAll();
            List<ClientDTO> clientDTOs = clientService.GetAll();
            string userId = HttpContext.Session.GetString("userId");
            ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

            var checkCart = listcart
                            .Where(x => x.GameId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            var checkStore = stores
                            .Where(x => x.GamesId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            if (checkCart == null && checkStore == null)
            {
                CartDTO cart = new CartDTO();
                cart.ClientId = client.ClientId;
                cart.GameId = gameId;
                cartService.Add(cart);

                List<CartViewModel> selectedCart = (from cartDTO in cartService.GetAll()
                                                    where cartDTO.ClientId == client.ClientId
                                                    join game in gamesService.GetAll() on cartDTO.GameId equals game.GamesId
                                                    select new CartViewModel
                                                    {
                                                        GameName = game.GameName,
                                                        Cost = game.Cost,
                                                        GameId = game.GamesId
                                                    }).ToList();

                int total = (int)selectedCart.Sum(x => x.Cost);
                ViewBag.Cart = selectedCart;
                ViewBag.total = total;

                HttpContext.Session.SetInt32("total", total);

                return View("~/Views/Shop/Cart.cshtml");
            }
            return RedirectToAction("Game", "Game", new { gameId = gameId });
        }

        public IActionResult CheckCart()
        {
			string userId = HttpContext.Session.GetString("userId");
            List<CartDTO> cartDTOs = cartService.GetAll();
			List<ClientDTO> clientDTOs = clientService.GetAll();
			ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

			List<CartViewModel> selectedCart = (from cartDTO in cartService.GetAll()
												where cartDTO.ClientId == client.ClientId
												join game in gamesService.GetAll() on cartDTO.GameId equals game.GamesId
												select new CartViewModel
												{
													GameName = game.GameName,
													Cost = game.Cost,
                                                    GameId = game.GamesId
                                                }).ToList();

            int total = (int)selectedCart.Sum(x => x.Cost);
            ViewBag.Cart = selectedCart;
            ViewBag.total = total;

            HttpContext.Session.SetInt32("total", total);
            return View("~/Views/Shop/Cart.cshtml");
		}
    }
}

WebApplication1/Controllers/InfoController.cs
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class InfoController : Controller
    {
        private readonly ITypeGameService typeGameService;
        private readonly IGamesService gamesService;
        private readonly IGamesTypesGamesService gamesTypesService;
        public InfoController(ILogger<HomeController> logger, ITypeGameService typeGame, IGamesService games,
            IGamesTypesGamesService gamesTypesService)
        {
            this.typeGameService = typeGame;
            this.gamesService = games;
            this.gamesTypesService = gamesTypesService;
        }
        [HttpPost]
        public IActionResult FindByGameName(SearchViewModel model)
        {
            if (model.GameName == null)
            {
                model.GameName = "";
            }
            List<GamesDTO> games = gamesService
                    .GetAll()
                    .Where(x => x.GameName.ToLower().Contains(model.GameName.ToLower()))
                    .ToList();

            ViewBag.games = games;
            ViewBag.count = games.Count();
            return View("~/Views/Information/SearchName.cshtml");
        }

        public IActionResult FindByTypeGame(int typeId) 
        {
            int TypeGameId = typeId;
            List<GamesDTO> games = gamesService.GetAll();
            List<GamesTypeGamesDTO> gamesTypeGames = gamesTypesService.GetAll();

			return View("~/Views/Information/SearchName.cshtml");
		}
    }
}

WebApplication1/Controllers/LoginController.cs
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using Microsoft.AspNetCore.Http;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
		private readonly SignInManager<User> signInManager;
		private readonly UserManager<User> userManager;

		public LoginController(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }
        [HttpPost]
		public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var result = signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false).Result;
                if (result.Succeeded)
                {
                    var user = await userManager.FindByNameAsync(model.Username);
                    HttpContext.Session.SetString("userId", user.Id);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Неправильный логин и (или) пароль");
                }
            }
            return View(model);
        }
        [HttpGet]
		public async Task<IActionResult> Logout()
		{
			await signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
		[HttpGet]
        public IActionResult Login() => View();

        public IActionResult Register() => View();
    }   
}

WebApplication1/Controllers/ProfileController.cs
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
	public class ProfileController : Controller
	{
		private readonly ITypeGameService typeGame;
		private readonly IUserService userService;
		private readonly UserManager<User> userManager;

		public ProfileController(ITypeGameService typeGame, IUserService userService, UserManager<User> userManager)
		{
			this.typeGame = typeGame;
			this.userService = userService;
			this.userManager = userManager;
		}
		public async Task<IActionResult> Profile()
		{
			List<TypeGameDTO> typeGameDTOs = typeGame.GetAll();
			string id = HttpContext.Session.GetString("userId");
			User user = await userManager.FindByIdAsync(id);

			ViewBag.typeGamesDTOs = typeGameDTOs;
			ViewBag.User = user;
            return View("~/Views/Information/Profile.cshtml");
		}

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] EditModel editModel)
        {
            if (ModelState.IsValid)
            {
                string userId = HttpContext.Session.GetString("userId");
                User user = await userManager.FindByIdAsync(userId);

                user.Email = editModel.Email;
                user.Birthday = editModel.Birthday;
                user.PhoneNumber = editModel.PhoneNumber;
                user.Address = editModel.Address;

                await userManager.UpdateAsync(user);

                ViewBag.User = user;

                return Json(new { success = true, data = editModel });
            }

            return Json(new { success = false });
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,500,0,200" />
	<style>
		.container {
			display: flex;
			justify-content: space-between;
		}

		.image-size {
			width: 175px;
			height: 250px;
		}

		.figure-container {
			display: flex;
			justify-content: center;
			margin-left: auto;
			margin-right: auto;
		}

			.figure-container figure {
				margin: 0 10px;
				min-width: 175px;
			}

		.a-hidden {
			white-space: nowrap;
			overflow: hidden;
			text-overflow: ellipsis;
			width: 170px;
			display: block;
			text-decoration: none;
		}

		.form1 {
			width: 60%;
		}

		.form2 {
			width: calc(30% - 10px);
		}

		.button-container {
			display: flex;
			flex-direction: column;
		}

			.button-container button {
				margin-bottom: 10px;
			}

		.w-94 {
			width: 94% !important;
		}

		.material-symbols-outlined {
			font-variation-settings: 'FILL' 0, 'wght' 500, 'GRAD' 200, 'opsz' 48
		}
	</style>
</head>
<body>
	@model WebApplication1.Models.SearchViewModel
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">KillerOfSteam</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Магазин</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Info" asp-action="Info">Информация</a>
						</li>
						<li class="nav-item col-sm-4 pt-1">
							<form asp-controller="Info" asp-action="FindByGameName" method="post">
								<div class="input-group">
									<input type="text" class="form-control form-control-sm" placeholder="Что будем искать?" asp-for="GameName" />
									<div class="input-group-append">
										<button class="btn btn-outline-light" type="submit">
											<span class="material-symbols-outlined">search</span>
										</button>
									</div>
								</div>
							</form>
						</li>

					</ul>
				</div>
				<div>
					<ul class="navbar-nav flex-lg-grow-0">	
						@if (User.IsInRole("Client"))
						{
							<li class="nav-item pt-1">
								<div class="input-group-append">
									<a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="CheckCart">
										<span class="material-symbols-outlined">
											shopping_basket
										</span>
									</a>
								</div>
							</li>
						}
						<li class="nav-item">
							@if (User.Identity.IsAuthenticated)
							{
							<li class="nav-item pt-1 dropdown">
								<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
										@User.Identity.Name
								</button>
								<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
									<li><a class="dropdown-item" asp-area="" asp-controller="Profile" asp-action="Profile" asp-route-username="@User.Identity.Name">Мой профиль</a></li>
										@if (User.IsInRole("Client"))
										{
											<li><a class="dropdown-item" asp-area="" asp-controller="Financial" asp-action="Wallet">Мой кошелек</a></li>
										}
										@if(User.IsInRole("Developer"))
										{
											<li><a class="dropdown-item" asp-area="" asp-controller="Game" asp-action="DeveloperMenu">Добавление игры</a></li>
										}
										@if(User.IsInRole("Moderator"))
										{
											<li><a class="dropdown-item" asp-area="" asp-controller="Game" asp-action="ModeratorMenu">Проверка запросов</a></li>
										}
										<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Выйти</a></li>
								</ul>
							</li>
							}
							else
							{
							<a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Login">Войти</a>
							}
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>