WebApplication1/Models/CartViewModel.cs
namespace WebApplication1.Models
{
    public class CartViewModel
    {
        public string GameName {  get; set; }
        public decimal Cost { get; set; }

        public int GameId { get; set; }
    }
}

WebApplication1/Models/ReplenishmentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class ReplenishmentViewModel
    {
        [Required(ErrorMessage = "Поле \"Номер карты\" обязательно для заполнения.")]
        [CreditCard(ErrorMessage = "Введите действительный номер кредитной карты.")]
        public string CardNumber { get; set; }

        [Required(ErrorMessage = "Поле \"Имя\" обязательно для заполнения.")]
        [StringLength(17, ErrorMessage = "Имя не может быть длиннее 17 символов.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Поле \"Фамилия\" обязательно для заполнения.")]
        [StringLength(25, ErrorMessage = "Фамилия не может быть длиннее 25 символов.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Поле \"Адрес выставления счета\" обязательно для заполнения.")]
        public string BillingAddress { get; set; }

        [Required(ErrorMessage = "Поле \"Город\" обязательно для заполнения.")]
        public string City { get; set; }

        [Required(ErrorMessage = "Поле \"Почтовый индекс\" обязательно для заполнения.")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Поле \"Страна\" обязательно для заполнения.")]
        public string Country { get; set; }

        [Required(ErrorMessage = "Поле \"Телефон\" обязательно для заполнения.")]
        [Phone(ErrorMessage = "Введите действительный номер телефона.")]
        public string Phone { get; set; }
        public int Cost { get; set; }
    }
}

WebApplication1/Controllers/CartController.cs
using DAL.Models;
using BLL.Services;
using Microsoft.AspNetCore.Mvc;
using BLL.Interfaces;
using BLL.DTO;
using DAL.Interface;
using AutoMapper;
using Microsoft.VisualBasic;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CartController : Controller
    {
        private IGamesService gamesService;
        private ICartService cartService;
        private IClientService clientService;
        private IStoreService storeService;
        public CartController(IGamesService gamesService, ICartService cartService, IClientService clientService, 
            IStoreService storeService)
        {
            this.gamesService = gamesService;
            this.cartService = cartService;
            this.clientService = clientService;
            this.storeService = storeService;
        }

        public IActionResult RemoveFromCart(int gameId)
        {
            List<CartDTO> listcart = cartService.GetAll();
            List<ClientDTO> clientDTOs = clientService.GetAll();

            string userId = HttpContext.Session.GetString("userId");
            ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

            var findCart = listcart
                            .Where(x => x.GameId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            if (findCart != null)
            {
                cartService.DeleteById(findCart);
            }

            return RedirectToAction("CheckCart");
        }
        public IActionResult AddToCart(int gameId)
        {
            List<CartDTO> listcart = cartService.GetAll();
            List<StoreDTO> stores = storeService.GetAll();
            List<ClientDTO> clientDTOs = clientService.GetAll();
            string userId = HttpContext.Session.GetString("userId");
            ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

            var checkCart = listcart
                            .Where(x => x.GameId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            var checkStore = stores
                            .Where(x => x.GamesId == gameId && x.ClientId == client.ClientId)
                            .FirstOrDefault();

            if (checkCart == null && checkStore == null)
            {
                CartDTO cart = new CartDTO();
                cart.ClientId = client.ClientId;
                cart.GameId = gameId;
                cartService.Add(cart);

                List<CartViewModel> selectedCart = (from cartDTO in cartService.GetAll()
                                                    where cartDTO.ClientId == client.ClientId
                                                    join game in gamesService.GetAll() on cartDTO.GameId equals game.GamesId
                                                    select new CartViewModel
                                                    {
                                                        GameName = game.GameName,
                                                        Cost = game.Cost,
                                                        GameId = game.GamesId
                                                    }).ToList();

                int total = (int)selectedCart.Sum(x => x.Cost);
                ViewBag.Cart = selectedCart;
                ViewBag.total = total;

                HttpContext.Session.SetInt32("total", total);

                return View("~/Views/Shop/Cart.cshtml");
            }
            return RedirectToAction("Game", "Game", new { gameId = gameId });
        }

        public IActionResult CheckCart()
        {
			string userId = HttpContext.Session.GetString("userId");
            List<CartDTO> cartDTOs = cartService.GetAll();
			List<ClientDTO> clientDTOs = clientService.GetAll();
			ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

			List<CartViewModel> selectedCart = (from cartDTO in cartService.GetAll()
												where cartDTO.ClientId == client.ClientId
												join game in gamesService.GetAll() on cartDTO.GameId equals game.GamesId
												select new CartViewModel
												{
													GameName = game.GameName,
													Cost = game.Cost,
                                                    GameId = game.GamesId
                                                }).ToList();

            int total = (int)selectedCart.Sum(x => x.Cost);
            ViewBag.Cart = selectedCart;
            ViewBag.total = total;

            HttpContext.Session.SetInt32("total", total);
            return View("~/Views/Shop/Cart.cshtml");
		}
    }
}

WebApplication1/Controllers/FinancialController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using BLL.Services;
using DAL.Models;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class FinancialController : Controller
    {
        private IClientService clientService;
        private ICartService cartService;
        private IGamesService gamesService;
        private IStoreService storeService;

        public FinancialController(IClientService clientService, ICartService cartService, IGamesService gamesService,
            IStoreService storeService)
        {
            this.clientService = clientService;
            this.cartService = cartService;
            this.gamesService = gamesService;
            this.storeService = storeService;
        }
        public IActionResult Wallet()
        {
            string userId = HttpContext.Session.GetString("userId");

            List<ClientDTO> clientDTOs = clientService.GetAll();
            ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

            ViewBag.Client = client;
            return View("~/Views/Shop/Wallet.cshtml");
        }

        public IActionResult Replenishment(int cost)
        {
            ViewBag.Cost = cost;

            return View("~/Views/Shop/Replenishment.cshtml");
        }
        public IActionResult Payment()
        {
            return View("~/Views/Shop/Payment.cshtml");
        }

        public IActionResult UpdateElectronicWallet(ReplenishmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                string userId = HttpContext.Session.GetString("userId");

                List<ClientDTO> clientDTOs = clientService.GetAll();
                ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();

                client.ElectronicWallet += model.Cost;
                clientService.Update(client);

                return RedirectToAction("Index", "Home");
            }
            return View("~/Views/Shop/Replenishment.cshtml");
        }
        public IActionResult BuyGames(CardViewModel cardViewModel)
        {
            if (ModelState.IsValid)
            {
                string userId = HttpContext.Session.GetString("userId");
                int total = (int)HttpContext.Session.GetInt32("total");

                List<ClientDTO> clientDTOs = clientService.GetAll();
                ClientDTO client = clientDTOs.Where(x => x.UserId == userId).FirstOrDefault();


                if (client.ElectronicWallet > total)
                {
                    List<CartDTO> listcart = cartService.GetAll();
                    List<CartDTO> cartListOfClient = listcart
                                .Where(x => x.ClientId == client.ClientId)
                                .ToList();

                    List<StoreDTO> stores = (from store in cartListOfClient
                                             join game in gamesService.GetAll() on store.GameId equals game.GamesId
                                             select new StoreDTO
                                             {
                                                 GamesId = game.GamesId,
                                                 ClientId = client.ClientId
                                             }).ToList();

                    foreach (var store in stores)
                    {
                        storeService.Add(store);
                    }
                    client.ElectronicWallet -= total;
                    clientService.Update(client);
                    foreach (var cart in cartListOfClient)
                    {
                        cartService.DeleteById(cart);
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View("~/Views/Shop/Payment.cshtml");
        }
    }
}

WebApplication1/Views/Shop/Cart.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Ваша корзина</h1>
@if (((IEnumerable<object>)ViewBag.Cart).Count() == 0)
{
    <h2>ПУСТО</h2>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Игра</th>
                <th class="text-right">Цена</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var line in @ViewBag.Cart)
            {
                <tr>
                    <td class="text-left">@line.GameName</td>
                    <td class="text-right">@line.Cost.ToString("# $")</td>
                    <td>
                        @Html.ActionLink("Удалить", "RemoveFromCart", "Cart", new { gameid = line.GameId }, new { @class = "btn purplecolor btn-lg mb-3" })
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2" class="text-right">Итого:</td>
                <td class="text-right">
                    @ViewBag.total
                </td>
            </tr>
        </tfoot>
    </table>
}
<div class="text-center">
    @Html.ActionLink("Вернутся к покупкам", "Index", "Home", null, new { @class = "btn purplecolor btn-lg mb-3" })
    @if (((IEnumerable<object>)ViewBag.Cart).Count() != 0)
    {
        @Html.ActionLink("Купить", "Payment", "Financial", null, new { @class = "btn purplecolor btn-lg mb-3" })
    }
</div>

WebApplication1/Views/Shop/Payment.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WebApplication1.Models.CardViewModel
<style>
    .form-control {
        width: 150%; 
    }
</style>
<div>
    <form method="post" asp-action="BuyGames" asp-controller="Financial" class="position-absolute">
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Номер карты</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="CardNumber" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-content-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Имя</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Фамилия</label>
            <div class="col-sm-12  px-4">
                <input type="text" class="form-control form-control-sm" asp-for="LastName" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Расчетный адрес</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="BillingAddress" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Город</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="City" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Почтовый индекс</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="PostalCode" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Страна</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="Country" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Телефон</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="Phone" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn purplecolor btn-lg mb-3">Купить</button>
    </form>
</div>

WebApplication1/Views/Shop/Replenishment.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model WebApplication1.Models.ReplenishmentViewModel
<style>
    .form-control {
        width: 150%;
    }
</style>
<div>
    <form method="post" asp-action="UpdateElectronicWallet" asp-controller="Financial" class="position-absolute">
        <h1>Пополнение баланса на @ViewBag.Cost.ToString("# $")</h1>
        <input type="hidden" asp-for="Cost" />
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Номер карты</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="CardNumber" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-content-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Имя</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Фамилия</label>
            <div class="col-sm-12  px-4">
                <input type="text" class="form-control form-control-sm" asp-for="LastName" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Расчетный адрес</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="BillingAddress" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Город</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="City" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Почтовый индекс</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="PostalCode" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Страна</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="Country" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>
        <div class="pt-3 row justify-context-start">
            <label class="col-sm-1 col-form-label px-0 text-black">Телефон</label>
            <div class="col-sm-12 px-4">
                <input type="text" class="form-control form-control-sm" asp-for="Phone" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn purplecolor btn-lg mb-3">Пополнить баланс</button>
    </form>
</div>

WebApplication1/Views/Shop/Wallet.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .parent {
        display: grid;
        grid-template-columns: 2.5fr 1fr;
        grid-template-rows: 1fr;
        grid-column-gap: 0px;
        grid-row-gap: 0px;
        }

    .div1 { grid-area: 1 / 1 / 2 / 2; }
    .div2 { grid-area: 1 / 2 / 2 / 3; }
</style>

<div class="parent">
    <div class="div1">
        <h2>ПОПОЛНИТЬ БАЛАНС КОШЕЛЬКА</h2>
        <p>Средства в вашем кошельке KillerOfSteam можно тратить на покупку любых игр </p>
        <div>
            <label>
                Добавить $5.00 USD
            </label>
            @Html.ActionLink("Пополнить баланс", "Replenishment", "Financial", new { cost = 5.0 }, new { @class = "btn purplecolor btn-lg mb-3" })
        </div>
        <div>
            <label>
                Добавить $10.00 USD
            </label>
            @Html.ActionLink("Пополнить баланс", "Replenishment", "Financial", new { cost = 10.0 }, new { @class = "btn purplecolor btn-lg mb-3" })
        </div>
        <div>
            <label>
                Добавить $25.00 USD
            </label>
            @Html.ActionLink("Пополнить баланс", "Replenishment", "Financial", new { cost = 25.0 }, new { @class = "btn purplecolor btn-lg mb-3" })
        </div>

        <div>
            <label>
                Добавить $50.00 USD
            </label>
            @Html.ActionLink("Пополнить баланс", "Replenishment", "Financial", new { cost = 50.0 }, new { @class = "btn purplecolor btn-lg mb-3" })
        </div>
        <div>
            <label>
                Добавить $100.00 USD
            </label>
            @Html.ActionLink("Пополнить баланс", "Replenishment", "Financial", new { cost = 100.0 }, new { @class = "btn purplecolor btn-lg mb-3" })
        </div>
    </div>
    <div class="div2">
        <h1>Ваш аккаунт KilleOfSteam</h1>
        <label>Остаток средств: @ViewBag.Client.ElectronicWallet.ToString("# $")</label>
    </div>
    

</div>
    